### ISSUE TITLE
Different versions

### ISSUE THREAD

**Issue by Galixte** [bruninoit/wvtt#9]
Hi,

I'm a french translator of phpBB extensions and i want to understand one thing for my french translation of your extension.

I have discovered your extension on phpBB.com and also on your website here: http://brunino.altervista.org/download/ I found the RC5 version and his date is on 2015.01.31

On GitHub, the date is 2015.03.09 and you have just change the number version for RC2: https://github.com/bruninoit/wvtt/commit/6e4fdd36d6b1ba64c57c1b608c70a040bf81c7ec

I want to know because in your RC5 version there are more language keys to translate than the RC2 version here on GitHub.

Why the RC5 version is older than the RC2 version ?

**Comment by bruninoit** [comment]
what extension?

**Comment by Galixte** [comment]
I'm talking about Who Visited This Topic, but it's a mistake i have confounded Top Ten Topics on your website and WWT. Sorry.
